name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m unittest discover -v

  package:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
    - uses: actions/checkout@v4
    
    - name: Build Debian package
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts debhelper
        ./bin/create-deb-package
    
    - name: Upload package artifact
      uses: actions/upload-artifact@v3
      with:
        name: hellou-deb
        path: dist/*.deb
    
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'release'
      with:
        files: dist/*.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
